name: Formatting (pre-commit)

on: push

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install clang-format-10
      run: sudo apt-get install clang-format-10
    - uses: pre-commit/action@v2.0.0
